Made Caches Generic
Before the change type hint such as TLRUCache[str, float] would have cause type checker such as mypy to raise an error
error: "TLRUCache" expects no type arguments, but 2 given  [type-arg]